name: CICD

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8000:8000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.10
          environment-file: src/environment.yml
          activate-environment: myenv

      - name: Install dependencies
        run: |
          conda install -c conda-forge rdkit
          pip install -r src/requirements.txt

      - name: Run flake8
        run: flake8 src --max-line-length=88

      - name: Run tests
        run: pytest src/test_main.py

      - name: Build and run Docker containers
        run: |
          docker-compose up -d --build
          until curl -s http://localhost:8000/; do
            echo "Waiting for service to start..."
            sleep 2
          done

      - name: Stop Docker containers
        run: docker-compose down
