version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_drug_app
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U admin -d drug_db
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  app:
    build: ./src
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    # networks:
    #   - webnet
    environment:
      DATABASE_URL: postgres://admin:password@postgres:5432/drug_db
  # app-2:
  #   build: ./src
  #   depends_on:
  #     - postgres
  #   # ports:
  #   #   - "8000:8000"
  #   networks:
  #     - webnet
  #   environment:
  #     DATABASE_URL: postgres://admin:password@postgres:5432/drug_db

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #   networks:
  #     - webnet
  #   depends_on:
  #     - app
  #     - app-2

volumes:
  pgdata:
    driver: local

# networks:
#   webnet:


# NGINX currently disabled!
