version: '3.8'

services:
  web1:
    build: ./src
    volumes:
      - ./src:/app
    environment:
      SERVER_ID: SERVER-1
    networks:
      - webnet

  web2:
    build: ./src
    volumes:
      - ./src:/app
    environment:
      SERVER_ID: SERVER-2
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2
    networks:
      - webnet

networks:
  webnet:
